### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by zeigerpuppy** [pzhaonet/bookdownplus#1]
Thanks for the package, looks like a good way to get to grips with bookdown.
However, I am finding some difficulties with initial install.

When I run the following command (I have tried on the latest OS X Rstudio or Ubuntu R console)
```R
bookdownplus::bookdownplus()
```

I get the following error 
```R
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'demo/index_.Rmd': No such file or directory
```

**Comment by pzhaonet** [comment]
It was a bug of the default template. I am sorry for that. Now it has been fixed. Please re-install it and try again.
