### ISSUE TITLE
the questions about bookdownplus

### ISSUE THREAD

**Issue by wong2016** [pzhaonet/bookdownplus#10]
**I run bookdownplus() in RStudio in win7, the information:**

processing file: thesis_classic.Rmd
  |.............                                                    |  20%
  ordinary text without R code

  |..........................                                       |  40%
label: fig1 (with options) 
List of 4
 $ fig.cap  : chr "caption"
 $ out.width: chr "80%"
 $ fig.align: chr "center"
 $ echo     : logi FALSE

  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: tab1 (with options) 
List of 2
 $ tidy: logi FALSE
 $ echo: logi FALSE

  |.................................................................| 100%
  ordinary text without R code

output file: thesis_classic.knit.md

"C:/PROGRA~2/Pandoc/pandoc" +RTS -K512m -RTS thesis_classic.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output thesis_classic.tex --table-of-contents --toc-depth 3 --template "tex\template_thesis_classic.tex" --number-sections --highlight-style tango --latex-engine pdflatex --natbib --chapters --variable tables=yes --standalone --bibliography bib/bib 
[pandoc.exe warning] --chapters is deprecated. Use --top-level-division=chapter instead.
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (MiKTeX 2.9.6210 64-bit)
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (MiKTeX 2.9.6210 64-bit)
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (MiKTeX 2.9.6210 64-bit)
entering extended mode

Output created: _book/thesis_classic.pdf
Warning messages:
1: running command '"pdflatex" -halt-on-error -interaction=batchmode "thesis_classic.tex"' had status 1 
2: running command '"pdflatex" -halt-on-error -interaction=batchmode "thesis_classic.tex"' had status 1 
3: running command '"pdflatex" -halt-on-error -interaction=batchmode "thesis_classic.tex"' had status 1 

**run sessionInfo(), the information:**

R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bookdownplus_1.3.0

loaded via a namespace (and not attached):
 [1] compiler_3.4.1  backports_1.1.0 magrittr_1.5    bookdown_0.4    rprojroot_1.2  
 [6] htmltools_0.3.6 tools_3.4.1     rstudioapi_0.6  yaml_2.1.14     Rcpp_0.12.12   
[11] stringi_1.1.5   rmarkdown_1.6   knitr_1.16      stringr_1.2.0   digest_0.6.12  
[16] evaluate_0.10.1

**also, I can't find the *.pdf in the _book/ fold, where only available thesis_classic.pdf and thesis_classic.tex.** 

how do I deal with this issue? thank you so much for your help!

**Comment by pzhaonet** [comment]
Thanks for the feedback, but I did not get it. What do you mean by * I can't find the .pdf in the _book/ fold, where only available thesis_classic.pdf and thesis_classic.tex*? thesis_classic.pdf is exactly the file you will get.
