### ISSUE TITLE
bookdownplus.Rproj

### ISSUE THREAD

**Issue by lightsquared** [pzhaonet/bookdownplus#11]
Having an issue where I run require(bookdownplus) and then bookdownplus() in a blank project and I get all the files except for the bookdownplus.Rproj.  Am I doing something wrong?

processing file: thesis_classic.Rmd
  |.............                                                    |  20%
  ordinary text without R code

  |..........................                                       |  40%
label: fig1 (with options) 
List of 4
 $ fig.cap  : chr "caption"
 $ out.width: chr "80%"
 $ fig.align: chr "center"
 $ echo     : logi FALSE

  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: tab1 (with options) 
List of 2
 $ tidy: logi FALSE
 $ echo: logi FALSE

  |.................................................................| 100%
  ordinary text without R code

output file: thesis_classic.knit.md

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS thesis_classic.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output thesis_classic.tex --table-of-contents --toc-depth 3 --template tex/template_thesis_classic.tex --number-sections --highlight-style tango --latex-engine /Library/TeX/texbin/pdflatex --natbib --chapters --variable tables=yes --standalone --bibliography bib/bib.bib 
Latexmk: This is Latexmk, John Collins, 5 Sep. 2016, version: 4.48.

Output created: _book/thesis_classic.pdf

**Comment by pzhaonet** [comment]
Thanks for the feedback. What is the version of your bookdownplus? In some early versions,  bookdownplus.Rproj is not created. Please update it to the latest version.
