### ISSUE TITLE
Can add SJTU thesis template?

### ISSUE THREAD

**Issue by bubifengyun** [pzhaonet/bookdownplus#12]
Here is link: https://github.com/weijianwen/SJTUThesis
There are 3 templates. Thank you.

**Comment by pzhaonet** [comment]
Thanks for the link. I will try but it is not guaranteed.

**Comment by bubifengyun** [comment]
非常开心，现在那个模板基本成型了。见 https://github.com/bubifengyun/SJTUThesis-Rmd 能够运行了。不过还有个问题，想请教一下您。您写的论文模板，对于论文要求图片有中英两种标题，如何实现的，谢谢了。

- https://github.com/yihui/knitr/issues/1554
- https://stackoverflow.com/questions/44049547/is-rmarkdown-supporting-multiple-captions

**Comment by bubifengyun** [comment]
Thank you, I had solved https://github.com/yihui/knitr/issues/1554

**Comment by pzhaonet** [comment]
祝贺！我在 windows 下用 RStudio，build 失败：

```
'make' is not recognized as an internal or external command,
operable program or batch file.

Exited with status 1.
```

**Comment by bubifengyun** [comment]
看错误原因是没有make这个软件，那个build 是通过makefile实现的，等后面，我修改一下，谢谢测试啊。

**Comment by bubifengyun** [comment]
抱歉，我今天试了一下，暂时没有解决办法，可能还需要在windows下安装 make 才可以。

**Comment by pzhaonet** [comment]
谢谢。能不能脱离 make？这样移植性会更好一点。

**Comment by bubifengyun** [comment]
理论上肯定可以，就是还没有找到解决办法，再试试看。

**Comment by pzhaonet** [comment]
我不太懂 linux，想问下为啥要依赖 make？能不能把这个范例按照 bookdown 最简单的默认框架来组织各个文件？比如文稿的 .Rmd 都放在根目录，tex 文件放到 /tex 文件夹，这样让新用户更容易上手一些。

`bookdownplus::share()` 会生成一个简单骨架。按这个骨架来安排示例文档，就可以很方便收到 bookdownplus 的模板库里。

**Comment by bubifengyun** [comment]
这个是在 https://github.com/yihui/bookdown-chinese 改过来的，一直在 make 里运行，我也在找办法，但是没有找到。

**Comment by pzhaonet** [comment]
嗯，同意，不过还是得看个人习惯吧。因为 bookdown 官方包的示例是放着根目录的，所以 bookdownplus 的示例也都把 .Rmd 放着了根目录里，并且为了简洁，书稿正文内容全部在 body.Rmd 一个文件里，这样对新手可能更友好一点。等新手熟悉了，自然会自己组织安排。

**Comment by bubifengyun** [comment]
刚刚更新了一下 pandoc 到 2.2.1，无法编译了，总是报错，等安装个 texlive 2018 再试试。现在先歇会，不折腾了。

**Comment by pzhaonet** [comment]
texlive 2018？有没有使用 tinytex？

**Comment by bubifengyun** [comment]
抱歉，最近家里矛盾比较多，这个最要紧，暂时停更。你可以先安装个 windows 版本的 Make 试试。谢谢测试。加油。

**Comment by pzhaonet** [comment]
好的。谢谢。

**Comment by bubifengyun** [comment]
现在我重新做了一个，在 https://github.com/bubifengyun/deepin-bible ，做成一个模板，我想修改一下发给你，可否？还是怎么弄。

**Comment by pzhaonet** [comment]
很漂亮的模板。如果想收进 bookdownplus，请以 pzhaonet/bookdownplus/inst/zip/ 下任何一个 .zip 文件为例，如 article.zip，解压缩这个文件，根据得到的文件夹来组织新模板的结构，即：

- 正文之前的 yaml 设置部分均写在 index.Rmd。 
- 正文全部写在 body.Rmd。
- 以上两个文件名里添加模板名称。
- 其他文件放进相应文件夹。
- 文件准备完毕后，压缩成一个 zip 文件，复制到 R 的library/bookdownplus/zip 下。
- 运行 `bookdownplus(template = your_new_template)`，看看得到的文件能否正常编译成书。

如果成功，请提交 PR 到本项目即可。

谢谢！

**Comment by bubifengyun** [comment]
好的。

**Comment by bubifengyun** [comment]
不能成功编译，我安装的稳定的 bookdownplus，不是通过 github 安装的 bookdownplus。在 *~/R/x86_64-pc-linux-gnu-library/3.4/bookdownplus* 没有 zip 文件夹，新建一个无效。难道要分开安装？谢谢。

**Comment by pzhaonet** [comment]
请通过 github 安装 bookdownplus。稳定版的已经太旧太不稳定了。我近期会做一次更新的。

**Comment by bubifengyun** [comment]
更新了，但是有问题报错

```
tlmgr search --file --global '/adobe'
! Critical ctex error: "fontset-unavailable"
! 
! CTeX fontset `adobe' is unavailable in current mode.
! 
! See the ctex documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

! 
! CTeX fontset `adobe' is unavailable in current mode.
! 
! See the ctex documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

! CTeX fontset `adobe' is unavailable in current mode.
! 
! See the ctex documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

! 
! See the ctex documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

! See the ctex documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

! 
! For immediate help type H <return>.
!...............................................  

! For immediate help type H <return>.
!...............................................  

错误: Failed to compile thesis_sjtu.tex. See thesis_sjtu.log for more info.
此外: There were 50 or more warnings (use warnings() to see the first 50)
Please delete thesis_sjtu.Rmd after you finish debugging the error.
```

搜索一下，说是要用 xelatex 才可以，不可用 pdflatex。可有办法解决? 谢谢。

**Comment by bubifengyun** [comment]
想起来了，需要把output.yaml文件也打包。这个里面还有很多相关配置呢。
