### ISSUE TITLE
Suggestion: Makefile and Article outline

### ISSUE THREAD

**Issue by bubifengyun** [pzhaonet/bookdownplus#13]
## Makefile 
It seems that it can run in R terminal without RStudio. eg.

```R
install.packages(xxx)
library(bookdownplus)
bookdownplus()
```

I add this command

```R
bookdownplus(template='thesis_mypku_zh')
```

If can edit in any editor, then `make pdf` (similar to this command), it will be better, in my opinion. That is to say, can add a Makefile for this template?

## Article outline

in *./_book*, I can see the pku.pdf file. I am so sorry that I can not find where every chapter's Rmd file is. Could you give a better outline template? Thank you.

**Comment by pzhaonet** [comment]
Thanks for the feedback. bookdownplus is independent on RStudio. Surely you can try a Makefile, and RStudio is fine with me.

The chapter's Rmd file is *body. Rmd*.

**Comment by bubifengyun** [comment]
3q
