### ISSUE TITLE
About templates

### ISSUE THREAD

**Issue by JVAQUEROM** [pzhaonet/bookdownplus#15]
I'd like to ask about the available templates. Where can I find a list with all of them? Is there some kind of repository where I can see other people's template and/or upload a new one?

I might create one template I am particularly interested in, but I'd like to see if somebody has done it before, so that I can save the time!

**Comment by pzhaonet** [comment]
It would be great if you created your own template. All the existing template files are in the folders of rmd\ style\ tex\. Good luck!

**Comment by JVAQUEROM** [comment]
I am finally preparing a template for Elsevier articles (there is one template from `rticles` package but it does not work in bookdown). How could upload it here so that everyone can benefit from it?

**Comment by pzhaonet** [comment]
Wow, great! Could you please have a look at the directory /inst/zip/. Each template is zipped in one zip file. I guess you could get a hint from these examples. So my suggestion would roughly be the following:

1. prepare your template which must be the same structure as other templates, including files and folders.
2. compress the files and folders into one sinlg zip file.
3. upload the zip file to the /inst/zip/ folder.

I have no time now, but I wish I could write a tutorial about how to contribute a template to bookdownplus in the near future. Your contribution would be much appreciated!

**Comment by JVAQUEROM** [comment]
I will do this in summer, when I have more spare time. I have not forgotten!!

**Comment by bubifengyun** [comment]
good job. I have done one https://github.com/bubifengyun/SJTUThesis-Rmd. it is not very difficult.

**Comment by pzhaonet** [comment]
Hi guys. I have updated bookdownplus recently, and built a new website to display and share bookdown templates. It is much easier than before. Feel free to upload your own template. <http://bookdownplus.netlify.com>
