### ISSUE TITLE
Error Building Demo Book

### ISSUE THREAD

**Issue by lehailey** [pzhaonet/bookdownplus#27]
Getting this error when building, using the latest version of pandoc:

output file: thesis_classic.knit.md

--chapters has been removed. Use --top-level-division=chapter instead.
Try pandoc.exe --help for more information.
Error: pandoc document conversion failed with error 2
In addition: Warning message:
running command '"C:/Users/lhailey/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS thesis_classic.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output thesis_classic.tex --table-of-contents --toc-depth 3 --template "tex\template_thesis_classic.tex" --number-sections --highlight-style tango --pdf-engine pdflatex --natbib --chapters --variable tables=yes --standalone' had status 2 
Please delete thesis_classic.Rmd after you finish debugging the error.

**Comment by pzhaonet** [comment]
Thanks for the feedback. Please make sure that the 'bookdown' package works properly before using 'bookdownplus'. The easiest way to check it is to created bookdown project (RStudio - New Project - New directory - Book Project using bookdown) and build it. Please refer to the bookdown package for details.

**Comment by lehailey** [comment]
I've successfully built a book with bookdown via that method and also built the bookdown demo book. I tried building from the bookdownplus() output and it is still giving the above error.

**Comment by yihui** [comment]
This might be the cause: https://github.com/pzhaonet/bookdownplus/blame/43e47e48c2bc3310cf304226628222b07c19be82/inst/proj/index.Rmd#L14

**Comment by pzhaonet** [comment]
@yihui would the `chapters`be the problem? I also have this warning but I simply ignore it and it works just fine...

**Comment by yihui** [comment]
I think the latest version of Pandoc has turned the warning into an error.

The tricky problem is that Pandoc < 2.0 does not support `--top-level-division=chapter`. Most users might be using Pandc 1.19.x because RStudio still ships that version. You have to change the argument according to user's pandoc version.

The easy fix for @lehailey is to manually correct this argument in index.Rmd of the project.

**Comment by pzhaonet** [comment]
@lehailey Great to hear that bookdown works properly. @yihui is right. I have just fixed it in the latest version of bookdownplus. You could simply resintall bookdownplus:

```
devtools::install_github("pzhaonet/bookdownplus")
```
and run the same script again to build the demo book, or you could modify the index.Rmd:

```
    pandoc_args:  --top-level-division=chapter
```

I guess I have to clear this error in all templates when I have time. If you have this error in other tempaltes, just modify the pandoc_args manually.

Good luck.

**Comment by lehailey** [comment]
Thank you both! 

However, I'm now getting this: 
output file: thesis_classic.knit.md

! Package babel Error: You haven't specified a language option.

Error: Failed to compile thesis_classic.tex. See thesis_classic.log for more info.
In addition: Warning message:
running command '"pdflatex" -halt-on-error -interaction=batchmode "thesis_classic.tex"' had status 1 
Please delete thesis_classic.Rmd after you finish debugging the error.
Execution halted

Exited with status 1.

I thought it was perhaps the tinytex  version due to a similar error being posted elsewhere, so updated to the latest dev version but still getting the same error.

Any help greatly appreciated.
Looking forward to trying out both packages by the way!

**Comment by pzhaonet** [comment]
I cannot reproduce your problem. It seems a problem with the LaTeX babel package. Please modify L.97 in tex/template_thesis_classic.tex as:

```
\usepackage[american]{babel}
```
and try again.

**Comment by Kongse** [comment]
`! Package babel Error: You haven't specified a language option.`

run in windows terminal: 
>tlmgr --gui

search for "babel-english" the install it, should solve the problem

**Comment by pzhaonet** [comment]
Thanks a lot for your feedback!

**Comment by lehailey** [comment]
After following the advice from kongse I can successfully build the bookdownplus demo now! Thanks everyone!

**Comment by lf-araujo** [comment]
Dear @yihui , sorry for bumping this old question, but adding ` pandoc_args: ["-F=pandoc-crossref", "--top-level-division=chapter"]` does not work anymore. An extra `--chapter` argument is still added to pandoc.

What am I doing wrong?

Best,
lf

**Comment by gepcel** [comment]
Check `pandoc --version`  maybe?
