### ISSUE TITLE
use `--top-level-division=chapter`  instead of `--chapters` for latest pandoc

### ISSUE THREAD

**Issue by dongzhuoer** [pzhaonet/bookdownplus#31]
similar to  rstudio/rmarkdown#1195

you may refer to [pandoc release note](http://pandoc.org/releases.html#pandoc-1.18-26-oct-2016) to decide how to specify argument according to the version of pandoc on user's OS

**Comment by pzhaonet** [comment]
Thank you! This issue was fixed in bookdownplus v.1.4.3. not updated on CRAN yet.
