### ISSUE TITLE
bookdownplus( )

### ISSUE THREAD

**Issue by markomerikukka** [pzhaonet/bookdownplus#33]
I tried to load bookdown demos with command bookdownplus( ). But I got an error message: 
"Output created: _book/thesis_classic.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file '_book/thesis_classic.pdf' does not exist
In addition: Warning message:
running command '"pdflatex" -halt-on-error -interaction=batchmode "thesis_classic.tex"' had status 1 
Please delete thesis_classic.Rmd after you finish debugging the error."

I don't know how to proceed.

**Comment by pzhaonet** [comment]
It seems that your LaTeX does not build the pdf file. Can you successfully build a pdf book with bookdown?
