### ISSUE TITLE
pandoc 2.2.1 

### ISSUE THREAD

**Issue by dmenne** [pzhaonet/bookdownplus#34]
With pandoc 2.2.1 and the default bookdownplus(), I get

--chapters has been removed. Use --top-level-division=chapter instead.

**Comment by bubifengyun** [comment]
it seems that you need modify *_out.yml* file, where in pandoc_args,

```
bookdown::pdf_book:
  keep_tex: yes
  dev: "cairo_pdf"
  latex_engine: xelatex
  citation_package: biblatex
  template: latex/template.tex
  pandoc_args: ["--listings", "--top-level-division=chapter"]
```

`--chapters` -> `--top-level-division=chapter`

**Comment by dmenne** [comment]
Thanks I had forgotten that I can change pandoc_args in  yml as a workaround. I keep this open, since it probable should be changed in code nevertheless.

**Comment by bubifengyun** [comment]
Yes, in bookdown, it had changed. but bookdownplus had not changed. The author of Bookdownplus may be too busy, so He did not notice it.
