### ISSUE TITLE
Error demo book and templates

### ISSUE THREAD

**Issue by LisaB92** [pzhaonet/bookdownplus#35]
Hey all! 
So.. I want to write my Bachelorthesis with bookdownplus. 
I'm working with R-3.5.1., installed the bookdownpackage version 0.8, bookdown 1.5.2. and tinytex 0.9. and it's Windows 7. 

If I run the code 
bookdownplus() 
I get the following error:
The github repo "pzhaonet/bookdownplus" cannot be connected. Thus only local templates are displayed.
[1] TRUE
Warning message:
In file(file, "rt") :
  cannot open file 'd:/github/bookdownplus/upload/-list.csv': Permission denied

There's no book folder in my working directory. 
After opening the .Rproj file and clicking on "build" I get the folder and a copernicus. pdf. 

Than I ran the following code in that file to create a book with another template (tried it with thesis_ubt, too):
bookdownplus::bookdownplus(template = "thesis_classic", more_output = 'word_document2', title = "Bachelor Thesis", author = "Lisa Bauer", render = FALSE, rproj = TRUE, output_name = "BA")

and got the following error:
The github repo "pzhaonet/bookdownplus" cannot be connected. Thus only local templates are displayed.
thesis_classic is unavailable. Please check whether your spelling is correct. Run get_template() to see available templates.
Warning message:
In file(file, "rt") :
  cannot open file 'd:/github/bookdownplus/upload/-list.csv': Permission denied

And if I run the get_template() code as suggested I get the same error like I got with bookdown()

Does anyone have a solution for me? 

Thanks a lot!

**Comment by LisaB92** [comment]
Does anyone have a solution for me? Thanks a lot!

**Comment by pzhaonet** [comment]
Hi, @LisaB92 . There was a stupid bug and I have just fixed it. Please reinstall `devtools::install_github('pzhaonet/bookdownplus')`.

**Comment by LisaB92** [comment]
Hi @pzhaonet ,
thanks a lot. Unfortunately bookdown() brings me the same error as before.

**Comment by LisaB92** [comment]
Tried it again today and it worked!!! Thanks so much!
