### ISSUE TITLE
Break chapters in different files

### ISSUE THREAD

**Issue by mnunes** [pzhaonet/bookdownplus#36]
So far, I was able to build a demo for `crc` book theme. However, there is something I cannot do: break my book into smaller files. I'd like to have one `.Rmd` file for Introduction, one `.Rmd` file for Methodology and so on. But I couldn't figure out how to do it. In fact, according to the following quote, I'm afraid I can't do it:

> You can see some other files (e.g. `index.Rmd`, `body.Rmd`, `-bookdownplus.Rproj`) and folders. Write your own texts in `body.Rmd` and revise the author and the book title in `index.Rmd`. You can use RStudio or any other text editor (but please don’t use Microsoft Word).

Is it possible to break my book into smaller files? I mean, more than only two, like the above quote seems to suggest is the only possible way.

**Comment by pzhaonet** [comment]
Sure, you can simply create multiple Rmd files . Please see [Chapter 1,3 of the bookdown book](https://bookdown.org/yihui/bookdown/usage.html).
