### ISSUE TITLE
How to render with R ?

### ISSUE THREAD

**Issue by galaxy001** [pzhaonet/bookdownplus#37]
I find this script always overwrite my writing.

How can I render with just R or Rscript ?

```
require('bookdownplus')
outypes=c("word_document2")
bookdownplus(template = 'docsens', render = TRUE, more_output=outypes)
```

**Comment by pzhaonet** [comment]
The bookdownplus package is used only for creating or initializing a bookdown book project. After the initialization, the bok should be rendered or built by the bookdown package. Please see the [bookdown book](https://bookdown.org/yihui/bookdown/) for more information.
