### ISSUE TITLE
Copernicus and several authors and affiliations

### ISSUE THREAD

**Issue by JVAQUEROM** [pzhaonet/bookdownplus#40]
The current "Copernicus" template does not properly support authors and affiliations. I know it is quite a difficult task (I feel unable to think of a way around this problem). But affiliations should have a number each, and the names of authors the number(s) of these affiliations.

Is there a way to connect them?

P.S.: I find that the main difficulty for me to modify the template is that I do not really know what the syntax is. Is there a name for the sintax in the template?

**Comment by pzhaonet** [comment]
Thanks for your comment. You are right. The 'copernicus' template for bookdown is not totally markdownized. The yaml header does not fully support the proper format of authors and affiliations. If you want to get it properly, you have play with LaTeX.

In the 'tex/template_article.tex' you can find:

```
$if(author)$
\author{$for(author)$$author$$sep$ \and $endfor$}
$endif$

$if(institute)$
\providecommand{\institute}[1]{}
\institute{$for(institute)$$institute$$sep$ \and $endfor$}
$endif$

%\author[]{NAME}
%\author[]{NAME}
%\author[]{NAME}

%\affil[]{ADDRESS}
%\affil[]{ADDRESS}
```

If the authors are Tom and Jerry, and the affiliations are Here and There, you can modify the texts above like this:


```
\author[1]{Thoms}
\author[2]{Jerry}

\affil[1]{Here}
\affil[2]{There}
```

In this way you are able to add multiple authors and affiliations.

Alternatively, the package 'rticles' has a similar template for  Copernicus journals I would suggest. However, it uses `base_format: rmarkdown::pdf_document`, which loses some features by bookdown. For convenience, I improved it in the package 'rosr', which I have developed recently. You could simply follow the [instruction](https://github.com/pzhaonet/rosr) and create an improved copernicus demo manuscript.
