### ISSUE TITLE
Error knitting pdf

### ISSUE THREAD

**Issue by LisaB92** [pzhaonet/bookdownplus#41]
Hey,

after writing some chapters into the body of my ubt file, I wanted to knit the pdf, but got the following error:

```
Could not find data file templates\tex\template_ubt.tex
Error: pandoc document conversion failed with error 97
Please delete ubt.Rmd after you finish debugging the error.
Execution halted
```
I'm not sure, if this is a bug or if I'm doing something wrong. 
I'm running bookdownplus with R3.5.2 on Windows 7.

My working directory looks like that:
- awi
    - _book
    - _bookdown_files
    - tex
    - ubt

I tried setting my working directory to "awi" or "ubt" and both didn't work. I also put the "tex" folder into a "template" folder. Copying the template_ubt.tex file into the ubt folder didn't work, too. 

Does anyone have any ideas? 
Thanks a lot.
Lisa

**Comment by pzhaonet** [comment]
It seemed weird that your computer was searching for 'templates\tex\template_ubt.tex'. In the yaml of index.Rmd, the path to the template should be

```
output:
  bookdown::pdf_book:
    template: tex/template_ubt.tex
```
by default. Could you please double check it? Or could you paste your yaml here?

**Comment by LisaB92** [comment]
My yaml looks exactly like you wrote it. 
I created a new book in another working directory and it seems to work just fine. So I guess there was a problem with my other working directory. 
Sorry for bothering and thanks for the reply.
