### ISSUE TITLE
Adding preface or acknowledgement before \mainmatter

### ISSUE THREAD

**Issue by caimiao0714** [pzhaonet/bookdownplus#43]
Hi Peng,

Is it possible to specify one or multiple *Rmarkdown chapters* as preface or acknowledgement before the \mainmatter in bookdown or bookdownplus?

My current solution is to add unnumbered chapters. However, they are still formal chapters with Arabic numerals. But I would prefer them to be Roman numerals before table of contents, list of figures and tables. Here is a snippet of my bookdown pdf output.

![image](https://user-images.githubusercontent.com/20736990/55584430-ca206480-56e9-11e9-8d64-c8870073ac4d.png)

I can add preface or acknowledgement in the latex template, but then I will have to write LaTeX syntex instead of concise markdown syntex.

Thanks,
Miao

**Comment by caimiao0714** [comment]
I actually have figured it out soon after I open the issue. What I did is just add `\mainmatter` at the end of the `preface.Rmd` file, and it works.

**Comment by pzhaonet** [comment]
Thanks for leaving your solution here!
