### ISSUE TITLE
dnd_dev is unavailable

### ISSUE THREAD

**Issue by myaseen208** [pzhaonet/bookdownplus#44]
The following code throws the error: `dnd_dev is unavailable`.

```
library('bookdownplus')
bookdownplus('dnd_dev', render = TRUE, rproj = TRUE)
dnd_dev is unavailable. Please check whether your spelling is correct. Run get_template() to see available templates.
```

Then I downloaded zip folder from [here][1] and tried to compile the document. However, it throws the error: 

    ! Undefined control sequence.
    l.61 \hypertarget
                     {chapter-1-bookdownplus}

Any hints to solve the issue. Thanks

  [1]: https://bookdownplus.netlify.com/portfolio/dnd/

**Comment by pzhaonet** [comment]
'dnd_dev' has been renamed as 'dnd'.
