### ISSUE TITLE
Constraining code chunk

### ISSUE THREAD

**Issue by pablobernabeu** [pzhaonet/bookdownplus#47]
Hello,

I'd like to ask about the possibility of constraining a code chunk inside the designated area. Specifically, in the [Copernicus example paper](https://bookdownplus.netlify.com/portfolio/copernicus/), a code chunk on Page 2 surpasses the right margin into the second column. I've tried to correct this by changing the indentation (in the discussion template in this case, because I can't render the `copernicus` format).

I've changed the indentation of the third line from the default one

```
bookdownplus::
  bookdownplus(template = 'article',
               more_output = c('html', 'word', 'epub'))
```

to this,

```
bookdownplus::
  bookdownplus(template = 'article',
  more_output = c('html', 'word', 'epub'))
```

to keep to the space in the `copernicus` format paper.

Yet, in the rendered document, the format didn't change. It was still 

```
bookdownplus::
  bookdownplus(template = 'article',
               more_output = c('html', 'word', 'epub'))
```

I'd be.really grateful for any advice.

**Comment by pzhaonet** [comment]
I guess the following might be a solution:
```
bookdownplus::
  bookdownplus(
    template = 'article',
    more_output = c('html', 'word', 'epub'))
```

**Comment by pablobernabeu** [comment]
Thanks a lot! I will check this shortly, and then close the issue.
