### ISSUE TITLE
scrpage2.sty not found

### ISSUE THREAD

**Issue by Gnossos** [pzhaonet/bookdownplus#51]
Following the instructions in the [readme.md for bookscanplus](https://github.com/pzhaonet/bookdownplus), `bd('ubt')` throws an error:
```
 ! LaTeX Error: File `scrpage2.sty` not found.
 ! Emergency stop.
```
Further investigation reveals [package "scrpage2" is obsolete and has been superseded by "scrlayer-scrpage."](https://tex.stackexchange.com/questions/541766/latex-error-file-scrpage2-sty-not-found)

Please fix or advise.

**Comment by pzhaonet** [comment]
Thanks. It is fixed. You can either comment the usage of package "scrpage2" or update bookdownplus to the newest version:

```
remotes::install_github("pzhaonet/bookdownplus")
library(bookdownplus)
bd('ubt')
```

**Comment by rachelledig** [comment]
The same error gets thrown when I run `bd('classic')` .

``! LaTeX Error: File `scrpage2.sty' not found.  ! Emergency stop.``.

I've installed the newest bookdownplus, as mentioned above and running `bd('ubt')` works great, however. Any advice?

**Comment by pzhaonet** [comment]
It is fixed. Please update bookdownplus to the newest version from github and try again.
