### ISSUE TITLE
article template - header - how to edit / remove

### ISSUE THREAD

**Issue by rainer-rq-koelle** [pzhaonet/bookdownplus#8]
Thanks for this package ... I love it!

Playing around with the article template, I fail to identify where and how to change the header on the first pages, i.e. the first 2 lines of the header reading:  "Manuscript prepared for J. Name
with version 4.2 of the LATEX class copernicus.cls."

The 3rd line of the header is correctly updated based on the Date in the YAML.
This is the print-out I can produce when building the book.

![template_article_header](https://user-images.githubusercontent.com/17096612/28214573-0aaa215a-68ab-11e7-83ba-ce46c0c623e9.png)

Thanks for pointing me in the right direction.

**Comment by pzhaonet** [comment]
Thanks for the feedback. I love it. too!

You have to play with the LaTeX code in style/copernicus.cls in your working directory. For example, remove or revise the following lines:

https://github.com/pzhaonet/bookdownplus/blob/master/inst/style/copernicus.cls#L1006

https://github.com/pzhaonet/bookdownplus/blob/master/inst/style/copernicus.cls#L1192

Then build your book again.

Good luck!

**Comment by rainer-rq-koelle** [comment]
Thanks for the pointer. Good stuff. Changing it by hand in copernicus.cls works (after some trial)  :)

I know too little so far about how to hook up knitr with Latex templates. How can one define the header as YAML and make the template render it?

**Comment by pzhaonet** [comment]
My pleasure. The answer is in the manual of bookdown, Chapter 4: https://bookdown.org/yihui/bookdown/templates.html
