### ISSUE TITLE
Miraculous

### ISSUE THREAD

**Issue by vfulco** [pzhaonet/bookdownplus#9]
No real place to leave praise.  After wrestling with bookdown/latex to write a book, the latter which I did not want to learn to any great degree as I have much bigger priorities as a budding entrepreneur, this code set facilitates real production level output.  Even adding a book cover caused my eyes to bleed in the unenhanced codeset (no disrespect to Yihui at all).  Well done, Sir.  You are a god among men ;-)

**Comment by pzhaonet** [comment]
Oh, I am much flattered. All this work is built on the basis of Yihui's `bookdown`. If any suggestions, please let him know.

Thanks for your feedback!
